#!/bin/bash

if [ -d /Volumes/OPT ]; then
    diskutil unmount $(df -h | grep OPT | awk '{ print $1 }' | sed 's/ntfs:\//\/dev/;s/\/OPT//')
    if [ $? != 0 ]; then
        exit 1
    else
        exit 0
    fi
else
    exit 2
fi
