#!/bin/bash

uptime

if [ "$USE_FULL_UPGRADE" == "true" ]; then
    pip3 list --outdated --format=freeze | awk -F "==" '{print $1}' | xargs -i pip3 install -U {}
fi
pip3 cache purge

if [ "$USE_FULL_UPGRADE" == "true" ]; then
    which aptitude &> /dev/null
    if [ $? == 0 ]; then
        sudo aptitude safe-upgrade
    fi
fi

if [ -d ~/.shellscript/ShellScript ]; then
    cd ~/.shellscript/ShellScript &> /dev/null
    git pull --rebase origin master
    cd - &> /dev/null
fi

sudo npm install --location=global npm

if [ -x ~/.shellscript/ShellScript/Operating\ System/Linux/RaspberryPi/temp ]; then
    ~/.shellscript/ShellScript/Operating\ System/Linux/RaspberryPi/temp cmd
fi

