#!/bin/bash

if [ ! -d /sys/class/leds ]; then
    echo "$(uname -srvmpio) is not supported. This script only works on Raspberry Pi. " >&2
    exit 1
fi

function NET_LEDController() {
    if [ ! -r /home/pi/.shellscript/lan951x-led-ctl/lan951x-led-ctl ]; then
        echo "Ethernet controller LEDs will not be controlled. Download the required source from https://github.com/dumpsite/lan951x-led-ctl" >&2
        return
    elif [ ! -x /home/pi/.shellscript/lan951x-led-ctl/lan951x-led-ctl ]; then
        echo "Unable to run lan951x-led-ctl script. Please check the permission." >&2
        return
    fi

    sudo sh -c "sudo /home/pi/.shellscript/lan951x-led-ctl/lan951x-led-ctl --fdx=s --lnk=$1 --spd=$2"
}

while true; do
    echo "Checking internet connection to www.google.com..."
    NET_LEDController 's' 's'
    ping -c 1 -W 1 -q "www.google.com" &> /dev/null
    if [ "$?" != "0" ]; then
        ping -c 1 -W 1 -q "192.168.0.50" &> /dev/null
        if [ "$?" != "0" ]; then
            echo "No internet connection and printer server is not responding."
            NET_LEDController 1 1
        else
            echo "No internet connection. However the printer server is responding."
            NET_LEDController 0 1
        fi
    else
        ping -c 1 -W 1 -q "192.168.0.50" &> /dev/null
        if [ "$?" != "0" ]; then
            echo "You have an internet connection. However the printer server is not responding."
            NET_LEDController 1 0
        else
            echo "You have an internet connection."
            NET_LEDController 0 0
        fi
    fi

    sleep $(shuf -i 5-15 -n 1)
done

