#!/bin/bash

function cpu_temp() {
    temp=$(vcgencmd measure_temp) 
    strcat=${temp:0:-2}
    strcat=${strcat:5}
    
    cpu=$(</sys/class/thermal/thermal_zone0/temp)
    int_temp=$((cpu/1000))

    if [ "$1" == "cmd" ]; then
        echo -n "temp="
    fi

    if [ $int_temp -ge 60 ]; then
        echo -en "\033[31m$strcat\033[32m'C\033[m"
    elif [ $int_temp -ge 50 ]; then
        echo -en "\033[33m$strcat\033[32m'C\033[m"
    elif [ $int_temp -ge 40 ]; then
        echo -en "\033[32m$strcat\033[32m'C\033[m"
    elif [ $int_temp -le 0 ]; then
        echo -en "\033[31m$strcat\033[32m'C\033[m"
    else
        echo -en "\033[34m$strcat\033[32m'C\033[m"
    fi

    system_throttle $1
}

function system_throttle() {
    temp=$(vcgencmd get_throttled)
    throttle=${temp:10}

    if [ "$throttle" == "0x1" -o "$throttle" == "0x10001" ]; then
        echo -e "    \033[33mWRN: The input power is currently unstable.\033[m"
    elif [ "$throttle" == "0x2" -o "$throttle" == "0x20002" ]; then
        echo -e "    \033[33mWRN: CPU frequency is currently limited.\033[m"
    elif [ "$throttle" == "0x4" -o "$throttle" == "0x40004" ]; then
        echo -e "    \033[33mWRN: $(hostname) is currently limited.\033[m"
    elif [ "$throttle" == "0x8" -o "$throttle" == "0x80008" ]; then
        echo -e "    \033[33mWRN: Temperature limit activated.\033[m"
    elif [ "$throttle" == "0x10000" ]; then
        echo -e "    \033[33mWRN: Under-voltage event has occurred.\033[m"
    elif [ "$throttle" == "0x20000" ]; then
        echo -e "    \033[33mWRN: CPU frequency limiting event has occurred.\033[m"
    elif [ "$throttle" == "0x40000" ]; then
        echo -e "    \033[33mWRN: Throttling has occurred.\033[m"
    elif [ "$throttle" == "0x80000" ]; then
        echo -e "    \033[33mWRN: Temp limiting event has occurred.\033[m"
    elif [ "$throttle" != "0x0" ]; then
        echo -e "    \033[33mthrottled=$throttle\033[m"
    else

	if [ "$1" == "cmd" ]; then
	    echo "    The current system isn't throttled."
	else
	    echo ""
        fi
    fi
}

cpu_temp $1
