#!/bin/bash

computerGeneralScore=0
spreadsheetScore=0
databaseScore=0
calcfuncflags=0

failureTest=0
correctAnswer=()

function usagePrint() {
    echo "이 스크립트는 컴퓨터 활용능력 필기 자격증 합격 여부를 판정하는데 도움을 줍니다."
    echo -e "\n\033[1;37m사용법\033[m"
    echo "calc [help|문제수 <플래그>]"
    echo -e "\n\033[1;37m파라미터 설명\033[m"
    echo -e " 문제수\t정오표와 답안지 입력을 원치않거나 이미 채점했을 경우 제공"
    echo -e " \t- 입력 순서: 컴퓨터 일반, 스프레드시트, 데이터베이스"
    echo -e " 플래그\t제공된 문제수 타입 기준 정의"
    echo -e " \t- 1: 문제수에 입력된 숫자는 정답 개수로 취급합니다."
    echo -e " \t- 0: 문제수에 입력된 숫자는 오답 개수로 취급합니다."
    echo -e " \t- 단, 자동 채점 및 판정 중 사용되는 플래그는 항상 1입니다."
    echo -e " help\t이 스크립트 도움말 표시"
    echo -e "\n\033[1;37m사용 예시\033[m"
    echo -e "calc help\t이 스크립트 도움말 표시"
    echo -e "calc\t\t정오표와 답안지를 제공하면 알아서 채점 및 판정"
    echo -e "calc 3 2 5 0\t각각 입력한 파라미터를 오답 개수로 취급하여 판정"
    echo -e "calc 17 18 15 1\t각각 입력한 파라미터를 정답 개수로 취급하여 판정"
    echo -e "\n\033[1;37m출력 결과\033[m"
    echo " - 컴퓨터 활용능력 필기 합격 여부"
    echo " - 각 과목별 점수 및 과락 여부"
    echo " - 전체 평균"
    echo -e "\n\033[1;37m판정 조건\033[m"
    echo "모든과목점수 >= 40 && 전체평균 >= 60"
    exit $1
}

function inputCheck() {
    if [[ $1 =~ [^1-4] ]]; then
        return 127
    elif [ x$1 == x ]; then
        return 127
    elif [ $1 -gt 4 -o $1 -lt 1 ]; then
        return 127
    else
        return $1
    fi
}

if [ $# -eq 0 ]; then
    clear
    for((i=1;i<=60;i++)); do
        while true; do
            echo "정답을 제공해 주세요. (1~4)"
            if [ $i -le 20 ]; then
                echo -n "[컴퓨터  일반] 정답 $i번 "
            elif [ $i -le 40 ]; then
                echo -n "[스프레드시트] 정답 $i번 "
            else
                echo -n "[데이터베이스] 정답 $i번 "
            fi
            read input

            inputCheck $input
            if [ $? == 127 ]; then
                echo -n "1 ~ 4 범위 내 정답을 입력해 주세요."
                read
                clear
            else
                correctAnswer+=($input)
                clear
                break
            fi
        done
    done

    for((i=1;i<=60;i++)); do
        while true; do
            if [ $i -le 20 ]; then
                echo "[컴퓨터  일반] 문항 $i번"
            elif [ $i -le 40 ]; then
                echo "[스프레드시트] 문항 $i번"
            else
                echo "[데이터베이스] 문항 $i번"
            fi
            echo -n "답안: "
            read answer

            inputCheck $answer
            if [ $? -eq 127 ]; then
                echo -n "1 ~ 4 범위 내 정답을 입력해 주세요."
                read
                clear
            else
                if [ $answer -eq ${correctAnswer[$(($i-1))]} ]; then
                    if [ $i -le 20 ]; then
                        computerGeneralScore=$(($computerGeneralScore+1))
                    elif [ $i -le 40 ]; then
                        spreadsheetScore=$(($spreadsheetScore+1))
                    else
                        databaseScore=$(($databaseScore+1))
                    fi
                fi
                clear
                break
            fi
        done
    done

    calcfuncflags=1
elif [ "$1" == "help" ]; then
    usagePrint 0
elif [ $# -eq 4 ]; then
    computerGeneralScore=$1
    spreadsheetScore=$2
    databaseScore=$3
    calcfuncflags=$4
else
    usagePrint 1
fi

if [[ $computerGeneralScore =~ [^0-9] ]]; then
    usagePrint 1
fi
if [[ $spreadsheetScore =~ [^0-9] ]]; then
    usagePrint 1
fi
if [[ $databaseScore =~ [^0-9] ]]; then
    usagePrint 1
fi

if [ $calcfuncflags -eq 0 ]; then
    computerGeneralScore=$((100-$computerGeneralScore*5))
    spreadsheetScore=$((100-$spreadsheetScore*5))
    databaseScore=$((100-$databaseScore*5))
elif [ $calcfuncflags -eq 1 ]; then
    computerGeneralScore=$(($computerGeneralScore*5))
    spreadsheetScore=$(($spreadsheetScore*5))
    databaseScore=$(($databaseScore*5))
fi

if [ $computerGeneralScore -lt 40 ]; then
    failureTest=1
fi
if [ $spreadsheetScore -lt 40 ]; then
    failureTest=1
fi
if [ $databaseScore -lt 40 ]; then
    failureTest=1
fi

result=$(($computerGeneralScore+$spreadsheetScore+$databaseScore))
result=$(($result/3))

if [ $result -ge 60 -a $failureTest -eq 0 ]; then
    echo "컴퓨터  일반: $computerGeneralScore"
    echo "스프레드시트: $spreadsheetScore"
    echo "데이터베이스: $databaseScore"
    echo -e "세과목  평균: $result\t[합  격]"
else
    if [ $computerGeneralScore -lt 40 ]; then
        echo -e "컴퓨터  일반: $computerGeneralScore\t[과  락]"
    else
        echo "컴퓨터  일반: $computerGeneralScore"
    fi
    if [ $spreadsheetScore -lt 40 ]; then
        echo -e "스프레드시트: $spreadsheetScore\t[과  락]"
    else
        echo "스프레드시트: $spreadsheetScore"
    fi
    if [ $databaseScore -lt 40 ]; then
        echo -e "데이터베이스: $databaseScore\t[과  락]"
    else
        echo "데이터베이스: $databaseScore"
    fi
    echo -e "세과목  평균: $result\t[불합격]"
fi

