#!/bin/bash

ls -a | grep ".git" &> /dev/null
if [ $? == 0 ]; then
    echo "listing large files which can't be uploaded to github..."
else
    echo "gitFileSize: cannot access '.git': no such file or directory"
    exit 1
fi

count=$(find . -size +50M -size -100M -and -not -path "./.git/objects/*" | grep -vf .gitignore | wc -l)
if [ $count -gt 1 ]; then
    echo -e "\033[33mthe $count files listed here are over the 50M limit."
    find . -size +50M -size -100M -and -not -path "./.git/objects/*" | grep -vf .gitignore | nl
elif [ $count -eq 1 ]; then
    echo -e "\033[33mthe $count file listed here are over the 50M limit."
    find . -size +50M -size -100M -and -not -path "./.git/objects/*" | grep -vf .gitignore | nl
else
    echo -e "\033[33mno such file. The 50M limit filter doesn't met the criteria."
fi

echo -e "\033[31m"
count=$(find . -size +100M -and -not -path "./.git/objects/*" | grep -vf .gitignore | wc -l)
if [ $count -gt 1 ]; then
    echo "the $count files listed here can't be uploaded to github over the 100M limit."
    find . -size +100M -and -not -path "./.git/objects/*" | grep -vf .gitignore | nl
elif [ $count -eq 1 ]; then
    echo "the $count file listed here can't be uploaded to github over the 100M limit."
    find . -size +100M -and -not -path "./.git/objects/*" | grep -vf .gitignore | nl
else
    echo -e "no such file. The 100M limit filter doesn't met the criteria."
fi
echo -e "\033[m"

