#!/bin/bash

echo "Listing large files which can't be uploaded to github..." 
echo -e "\033[37mNOTE: Large file searches will be done relative to the $(pwd) directory.\033[m" 

echo -e "\033[33mThe files listed here are over the 80M limit."
count=$(find . -size +80M -size -100M | wc -l)
if [ $count -ne 0 ]; then
    find . -size +80M -size -100M
else
    echo -e "\tNo such file. The filter doesn't met the criteria."
fi
echo -e "\033[31m"

echo "The files listed here can't be uploaded to github over the 100M limit."
count=$(find . -size +100M | wc -l)
if [ $count -ne 0 ]; then
    find . -size +100M
else
    echo -e "\tNo such file. The filter doesn't met the criteria."
fi
echo -e "\033[m"

