#!/bin/bash

which osascript &> /dev/null
if [ $? != 0 ]; then
    exit 1
fi

killall -u $USER "KIM_Extension" &> /dev/null
if [ $? == 0 ]; then
    osascript -e 'tell app "System Events" to display alert "한국어 IM을(를) 다시 시작하였습니다."'
else
    osascript -e 'tell app "System Events" to display alert "한국어 IM을(를) 다시 시작하지 못했습니다. 그런 프로세스가 없습니다."'
fi

killall -du $USER "Safari" &> /dev/null
if [ $? == 0 ]; then
    osascript -e 'tell app "System Events" to display dialog "Safari을(를) 다시 시작하시겠습니까? 모든 저장되지 않은 변경사항은 유실될 수 있습니다."' &> /dev/null
    if [ $? == 0 ]; then
        killall -u $USER "Safari" &> /dev/null
        if [ $? == 0 ]; then
            open /Applications/Safari.app
        fi
    fi
fi
