#!/bin/bash

motdPath=/etc/motd

remotelogin_on() {
    sudo systemsetup -setremotelogin on
    sudo systemsetup -getremotelogin
    sudo systemsetup -setcomputersleep never
    ifconfig | egrep "(inet )"
}

remotelogin_off() {
    sudo systemsetup -f -setremotelogin off
    sudo systemsetup -getremotelogin
    sudo systemsetup -setcomputersleep 10
    who
}

remotelogin_status() {
    sudo systemsetup -getremotelogin
    sudo systemsetup -getsleep
    ifconfig |egrep "(inet )"
    ping -c 2 -W 1 -q "www.google.com" &> /dev/null
    if [ "$?" != "0" ]; then
        echo "Internet: Disconnected"
    else
        echo "Internet: Connected"
    fi
}

if [ "$1" == "off" ]; then
    remotelogin_off
elif [ "$1" == "on" ]; then
    remotelogin_on
elif [ "$1" == "status" ]; then
    remotelogin_status
elif [ "$1" == "help" ]; then
    echo "OVERVIEW: change remotelogin setting"
    echo -e "\033[0;1mREQUIRED\033[m: root or authorized user only run below function"
    echo "USAGE: $0 [option]"
    echo "OPTIONS: "
    echo -e "    on: remotelogin enable\n   off: remotelogin disable"
    echo -e "status: remotelogin status\n  help: help this script"
else            # parameter error
    if [ x$1 == x ]; then
        echo "USAGE: $0 [option]"
        echo "Please add help and will see help for this script."
    else
        echo -e "\033[31mERR\033[m: command not found: $1"
        echo "Please change $1 to help and will see help for this script."
    fi
    exit 1
fi
exit 0
