#!/bin/bash

firefox_path=/usr/share/applications/firefox.desktop
chromium_path=/usr/share/applications/chromium.desktop
vivaldi_path=/usr/share/applications/vivaldi-stable.desktop

function remap() {
    if ! [ -r $1 ]; then
        echo "reason: $1 no such file or directory." >&2
        return 1
    fi

    lsattr -l $1 | grep Immutable &> /dev/null
    if [ $? -ne 0 ]; then
        if [ -w $1 ]; then
            sed -i "s|/usr/bin/$(basename $1 .desktop)|/usr/local/bin/$(basename $1 .desktop | sed 's/-.*//g')|g" $1
            sed -i "s|/usr/lib/$(basename $1 .desktop)|/usr/local/bin|g" $1
        else
            echo "error: unable to write $1. Access denied." >&2
            return 1
        fi
    else
        echo "error: unable to write $1. Immutable flags enabled." >&2
        return 1
    fi
}

remap $firefox_path
remap $chromium_path
remap $vivaldi_path

update-desktop-database
