#!/bin/bash

target=$(basename $0 | sed 's/-.*//')

if [ "$target" == "firefox" ]; then
    nice -n 5 /usr/bin/$target $@
else
    current_workspace=$(inxi -S | grep Desktop | awk '{ print $2 }')
    if [ "$current_workspace"  == 'Sway' ]; then
        nice -n 10 /usr/bin/$target $@
    else
        notify-send --action='1=OK' "Unable to launch $target." "Aborted due to invalid workspace: $current_workspace. reason: Possible conflict chromium-keychain configuration."
        exit 1
    fi
fi
