#!/bin/bash

projectName=`basename "$PWD"`
aggressive=0

if [ "$1" == "-a" -o "$1" == "--aggressive" ]; then
    aggressive=1
fi

if [ "$1" == "-h" -o "$1" == "--help" ]; then
    echo "usage: $0 [option|uproject]"
    echo -e "-h, --help\t\t\tShow this help"
    echo -e "-a, --aggressive\t\tRemove IDE config caches"
    exit 0
elif [ $# -eq 1 -a -d "$1" ]; then
    cd "$1" &> /dev/null
    if [ $? -eq 0 ]; then
        projectName=`basename "$PWD"`
    else
        echo "unable to access $1. Please check permission." >&2
    fi
elif [ $# -eq 1 -a -f "$1" ]; then
    projectName=`basename "$1" | sed 's/\.uproject//'`
    target=$(echo "$1" | sed "s/$projectName\.uproject//")
    cd "$target"
    exit 1
elif [ $# -ne 0 ]; then
    echo "usage: $0 [option|uproject]"
    exit 1
fi

if [ -r "$projectName.uproject" ]; then
    rm -rf Binaries DerivedDataCache Intermediate
    rm -rf Saved/Autosaves Saved/Collections Saved/ShaderDebugInfo
    rm Makefile

    if [ $aggressive -eq 1 ]; then
        rm -rf .idea .vscode Saved
        rm *.code-workspace *.DotSettings.user
    fi
else
    echo "unable to cleanup $projectName project. reason: $PWD does not seem UnrealProject directory structure." >&2
fi
