#!/bin/bash

enginePath="$(echo $UEPath)"
projectName=`basename "$PWD"`
realPath=$(echo "$PWD/$projectName.uproject")

if [ "$1" == "-h" -o "$1" == "--help" ]; then
    echo "usage: $0 [option|uproject]"
    echo -e "-h, --help\t\t\tShow this help"
    exit 0
elif [ $# -eq 1 -a -d "$1" ]; then
    cd "$1" &> /dev/null
    if [ $? -eq 0 ]; then
        projectName=`basename "$1"`
        realPath=$(echo "$1/$projectName.uproject")
    else
        echo "unable to access $1. Please check permission." >&2
    fi
elif [ $# -eq 1 -a -f "$1" ]; then
    projectName=`basename "$1" | sed 's/\.uproject//'`
    realPath="$1"
elif [ $# -ne 0 ]; then
    echo "usage: $0 [option|uproject]"
    exit 1
fi

if [ -r "$projectName.uproject" ]; then
    cd "$enginePath"
    if ! [ -x "$enginePath/GenerateProjectFiles.sh" ]; then
        echo "unable to generate $projectName project. reason: $enginePath does not exist or access deined." >&2
        exit 1
    fi

    bash -c "./GenerateProjectFiles.sh -engine -game \"$realPath\""
else
    echo "unable to generate $projectName project. reason: $PWD does not seem UnrealProject directory structure." >&2
    exit 1
fi
