#!/bin/bash

if [ $# -eq 0 ]; then
    echo -e "\e[31mERR\e[m: Fatal: Please provide screen resolution. (example: $0 1024 768)"
    exit 1
fi

bgfile=/tmp/wallpaper.jpg
bgdownloc=https://unsplash.it/$1/$2/?random
pingloc=www.google.com

if [ $UID -ne 0 ]; then
    echo -e "\e[31mERR\e[m: Fatal: Please check \e[0;1m$bgfile\e[m permission. are you root?"
    exit 1
fi

rm -f $bgfile
while true; do
    ping -c 1 -W 1 -q $pingloc &> /dev/null
    if [ "$?" == "0" ]; then
        wget -O $bgfile $bgdownloc &> /dev/null
        if [ "$?" != "0" ]; then
            continue
        fi
        break
    else
        echo -e "\e[31mERR\e[m: Please check your network connection."
        sleep 2
    fi
done

gsettings set org.cinnamon.desktop.background picture-uri file://$bgfile &> /dev/null
echo -e "\e[34mOK\e[m: Successfully changed desktop background."
exit 0

