#!/bin/bash

errorCount=0

function searchSparkle() {
    if [ -d "$1" ]; then
        echo -e "\n\033[0;1mCheck for updates manually for the apps below that use the Sparkle framework.\033[m"
        echo "--- $2 Applications ---"
        find "$1" -name Sparkle.framework -maxdepth 7 -mindepth 3 1> ~/Library/Logs/find.log 2> /dev/null
        if [ "$(cat ~/Library/Logs/find.log)" == "" ]; then
            echo -e "\033[33mWRN\033[m: Sparkle framework not found in \033[0;4m$1\033[m"
        else
            grep -ioE '.*\.app' ~/Library/Logs/find.log > ~/Library/Logs/find1.log 2>/dev/null
            while read line; do
                appVersion=$(mdls -raw -name kMDItemVersion "$line")
                echo "$line ($appVersion)" >> ~/Library/Logs/find2.log
            done < ~/Library/Logs/find1.log

            nl ~/Library/Logs/find2.log

            rm ~/Library/Logs/find.log ~/Library/Logs/find1.log ~/Library/Logs/find2.log 2> /dev/null
        fi
    else
        echo -e "\n\033[33mWRN\033[m: searchSparkle: no such directory: \033[0;4m$1\033[m"
    fi
}

pip3 install --upgrade pip
if [ $? != 0 ]; then
    if [ $LANG == "ko_KR.UTF-8" ]; then
        echo "pip3 을 업데이트 하는 도중 에러가 발생하였습니다. "
    else
        echo "An error occured when updating pip3."
    fi
    errorCount=$((errorCount+1))
fi


if [ $LANG == "ko_KR.UTF-8" ]; then
    echo "MacVim.app 가상본 만드는 중..."
else
    echo "Creating MacVim.app alias..."
fi
if [ "$(uname -m)" == "arm64" ]; then
    if [ "$(which brew)" == "/usr/local/bin/brew" ]; then
        macvimPath=$(find /usr/local/Cellar/macvim -name "MacVim.app")
    else
        macvimPath=$(find /opt/homebrew/Cellar/macvim -name "MacVim.app")
    fi
else
    macvimPath=$(find /usr/local/Cellar/macvim -name "MacVim.app")
fi
if [ "$macvimPath" != "" ]; then
    ln -sF $macvimPath ~/Applications/
    if [ $? == 0 ]; then
        if [ $LANG == "ko_KR.UTF-8" ]; then
            echo "MacVim.app 가상본을 성공적으로 만들었습니다."
        else
            echo "Successfully create MacVim.app alias."
        fi
    else
        if [ $LANG == "ko_KR.UTF-8" ]; then
            echo "MacVim.app 가상본을 만드는데 에러가 발생하였습니다."
        else
            echo "Failed to create MacVim.app alias."
        fi
        errorCount=$((errorCount+1))
    fi
fi

softwareupdate -l
if [ $? != 0 ]; then
    errorCount=$((errorCount+1))
fi

mas outdated
if [ $? != 0 ]; then
    errorCount=$((errorCount+1))
fi

pipupgrade --latest -y
if [ $? != 0 ]; then
    errorCount=$((errorCount+1))
fi

pip3 cache purge
if [ $? != 0 ]; then
    errorCount=$((errorCount+1))
fi

searchSparkle "/Applications" "System"
searchSparkle "/Volumes/External/Applications" "External"
searchSparkle "$HOME/Applications" "User"
searchSparkle "/Volumes/External$HOME/Applications" "External User"

/bin/zsh -c "source ~/.zshrc; which omz > /dev/null 2>&1"
if [ $? == 0 ]; then
    /bin/zsh -c "source ~/.zshrc; omz update && exit"
    if [ $? != 0 ]; then
        errorCount=$((errorCount+1))
    fi
fi


if [ $errorCount -gt 0 ]; then
    exit 1
else
    exit 0
fi
