#!/bin/bash

which open > /dev/null
if [ $? != 0 ]; then
    exit 1
fi

echo -n "Launching KakaoTalkAdBlock application ... "
if [ -r "/mnt/c/Users/$USER/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/KakaoTalkAdBlock/KakaoTalkAdBlock.appref-ms" ]; then
    open "/mnt/c/Users/$USER/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/KakaoTalkAdBlock/KakaoTalkAdBlock.appref-ms" &
else
    echo -e "\nUnable to locate KakaoTalkAdBlock."
    open "https://github.com/blurfx/KakaoTalkAdBlock"
    exit 1
fi

sleep 5
echo "Done."

echo -n "Launching KakaoTalk application ... "
if [ -r "/mnt/c/Program Files (x86)/Kakao/KakaoTalk/KakaoTalk.exe" ]; then
    open "/mnt/c/Program Files (x86)/Kakao/KakaoTalk/KakaoTalk.exe"
    echo "Done."
    exit 0
else
    echo -e "\nUnable to locate KakaoTalk."
    open "https://kakao.io/?lang=KR"
    exit 1
fi

