#!/bin/bash

ExitDelaySeconds=10
CurrentElapsedTime=0

which open > /dev/null
if [ $? != 0 ]; then
    exit 1
fi
which taskkill.exe > /dev/null
if [ $? != 0 ]; then
    exit 1
fi

which powershell.exe > /dev/null
if [ $? != 0 ]; then
    exit 1
fi

echo -n "Launching KakaoTalkAdBlock application ... "
if [ -r "/mnt/c/Users/$USER/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/KakaoTalkAdBlock/KakaoTalkAdBlock.appref-ms" ]; then
    KakaoTalkAdBlockPID=$(powershell.exe -Command '(Get-Process KakaoTalkAdBlock).id' 2> /dev/null)
    if [ "$KakaoTalkPID" != "" ]; then
        taskkill.exe -F -IM KakaoTalkAdBlock.exe &> /dev/null
    fi
    sleep 1
    open "/mnt/c/Users/$USER/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/KakaoTalkAdBlock/KakaoTalkAdBlock.appref-ms" &
    if [ $? != 0 ]; then
        powershell.exe '(New-Object -ComObject Wscript.Shell).Popup("Unable to launch KakaoTalkAdBlock.",0,"KakaoTalkLauncher",0x10)' &> /dev/null
        echo -e "\nUnable to launch KakaoTalkAdBlock. Please check permission. Aborting." >&2
        exit 1
    else
        sleep 5
        echo "Done."
    fi
else
    powershell.exe '(New-Object -ComObject Wscript.Shell).Popup("Unable to locate KakaoTalkAdBlock.",0,"KakaoTalkLauncher",0x10)' &> /dev/null
    echo -e "\nUnable to locate KakaoTalkAdBlock." >&2
    open "https://github.com/blurfx/KakaoTalkAdBlock"
    exit 1
fi

echo -n "Launching KakaoTalk application ... "
if [ -r "/mnt/c/Program Files (x86)/Kakao/KakaoTalk/KakaoTalk.exe" ]; then
    open "/mnt/c/Program Files (x86)/Kakao/KakaoTalk/KakaoTalk.exe"
    echo "Done."
else
    powershell.exe '(New-Object -ComObject Wscript.Shell).Popup("Unable to locate KakaoTalk.",0,"KakaoTalkLauncher",0x10)' &> /dev/null
    echo -e "\nUnable to locate KakaoTalk." >&2
    KakaoTalkAdBlockPID=$(powershell.exe -Command '(Get-Process KakaoTalkAdBlock).id' 2> /dev/null)
    if [ "$KakaoTalkPID" != "" ]; then
        taskkill.exe -F -IM KakaoTalkAdBlock.exe &> /dev/null
    fi
    open "https://kakao.io/?lang=KR"
    exit 1
fi

echo -n "Waiting untill KakaoTalk application exited ... "
while true; do
    KakaoTalkPID=$(powershell.exe -Command '(Get-Process KakaoTalk).id' 2> /dev/null)
    if [ x"$KakaoTalkPID" == x ]; then

        if [ $CurrentElapsedTime -lt $ExitDelaySeconds ]; then
            sleep 1
            CurrentElapsedTime=$(($CurrentElapsedTime+1))
            continue
        fi

        taskkill.exe -F -IM KakaoTalkAdBlock.exe > /dev/null
        if [ $? != 0 ]; then
            powershell.exe '(New-Object -ComObject Wscript.Shell).Popup("Unable to terminate KakaoTalkAdBlock.",0,"KakaoTalkLauncher",0x30)' &> /dev/null
            echo -e "\nUnable to terminate KakaoTalkAdBlock. Please exit KakaoTalkAdBlock manually." >&2
            exit 1
        else
            echo "Done."
            exit 0
        fi
    else
        CurrentElapsedTime=0
    fi
    sleep 1
done

