#!/bin/bash

if [ $# -eq 0 -a -t 0 ]; then
    echo "Usage: newline [options] [<files>]"
    exit 2
elif [ "$1" == "-i" -o "$1" == "--info" ]; then
    next_line=0
    if [ -t 0 ]; then
        params=("$@")
    else
        params=("$@" $(cat /dev/stdin))
    fi
    for i in "${!params[@]}"; do
        if [[ "${params[$i]}" != "-"* ]]; then
            if [ -d "${params[$i]}" ]; then
                change_params=$(echo "${params[$i]}" | sed 's/\/$//')
                echo "Please change ${params[$i]} to $change_params/*"
            elif [ -f "${params[$i]}" ]; then
                file "${params[$i]}" 2> /dev/null
                xxd -l 64 "${params[$i]}"
                next_line=1
            fi
        fi

        if [ $(($#-1)) -ne $i -a $next_line -ne 0 ]; then
            echo ""
        fi
    done
    exit 0
elif [ "$1" == "-h" -o "$1" == "--help" ]; then
    echo 'Determine type of files or converting EOL between LF and CRLF.'
    echo -e '\nUsage: newline [options] [<files>]'
    echo -e '\nOptions: '
    echo -e ' -h, --help\t\tdisplay this help and exit'
    echo -e ' -i, --info FILEs\tdisplay provide file type and properties'
    echo -e '     --type=EOL\t\tlimiting `EOL` type when using converter'
    echo -e '\t\t\t`EOL` only accepted `CRLF` and `LF` (NAK `\\n` or `\\r\\n`)'
    echo -e ' FILEs\t\t\tconverting files EOL in provided params'
    echo -e '\nEXIT STATUS'
    echo -e ' 0\t operation Successful'
    echo -e ' 1\t operation Failed'
    echo -e ' 2\t unknown command or parameter type'
    echo -e '\nEXAMPLES'
    echo 'Print example.txt file EOL type and properties'
    echo '% newline -i example.txt'
    echo ''
    echo 'Convert example.txt file other support EOL type'
    echo '% newline example.txt'
    echo ''
    echo 'Convert example.txt file EOL type to CRLF'
    echo '% newline --type=CRLF example.txt'
    echo ''
    echo "Convert files EOL type to LF recursively from specified directory"
    echo "% find /path/to/directory -type f | newline --type=LF"
    exit 0
fi

constantEOF=""
if [ -t 0 ]; then
    params=("$@")
else
    params=("$@" $(cat /dev/stdin))
fi

for i in "${!params[@]}"; do
    if [[ "${params[$i]}" == "-"* ]]; then
        if [ "${params[$i]}" == "--type=LF" -o "${params[$i]}" == "--type=lf" ]; then
            constantEOF="LF"
        elif [ "${params[$i]}" == "--type=CRLF" -o "${params[$i]}" == "--type=crlf" ]; then
            constantEOF="CRLF"
        fi
        continue
    fi

    if [ -d "${params[$i]}" ]; then
        change_params=$(echo "${params[$i]}" | sed 's/\/$//')
        echo "Please change ${params[$i]} to $change_params/*"
    fi

    file -b "${params[$i]}" 2> /dev/null | grep "text" 2> /dev/null | grep "CRLF" &> /dev/null
    if [ $? == 0 ]; then
        if [ "$constantEOF" == "CRLF" ]; then
            echo "skipping ${params[$i]} file. reason: requirement already satisfied.">&2
            continue
        fi
        sed -i 's/\r$//' "${params[$i]}" &> /dev/null
        if [ $? == 0 ]; then
            echo "${params[$i]}: operation complete. EOL was converted CRLF to LF."
        else
            echo "unable to convert ${params[$i]} file. reason: access denied.">&2
        fi
        continue
    fi

    file -b "${params[$i]}" 2> /dev/null | grep "text" 2> /dev/null | grep "CR" &> /dev/null
    if [ $? == 0 ]; then
        echo "unable to convert ${params[$i]} file. reason: unsupported EOL CR(Macintosh) type.">&2
        continue
    fi

    file -b "${params[$i]}" 2> /dev/null | grep "text" &> /dev/null
    if [ $? == 0 ]; then
        if [ "$constantEOF" == "LF" ]; then
            echo "skipping ${params[$i]} file. reason: requirement already satisfied.">&2
            continue
        fi
        sed -i 's/$/\r/' "${params[$i]}" &> /dev/null
        if [ $? == 0 ]; then
            echo "${params[$i]}: operation complete. EOL was converted LF to CRLF."
        else
            echo "unable to convert ${params[$i]} file. reason: access denied.">&2
        fi
        continue
    fi
done

