#!/bin/bash

shouldProjectClean=0

if [ x"$1" == x ]; then
    echo "usage: $0 [option] <[build-options [build-options1.2..]] [build-preset]>" >&2
    exit 1
elif [ "$1" == "help" -o "$1" == "--help" ]; then
    echo "usage: $0 [option] <[build-options [build-options1.2..]] [build-preset]>"
    echo ""
    echo "OPTIONS"
    echo -e "   help\tShow this manual"
    echo -e "  clean\tDelete caches and object files (UnrealEditor only)"
    echo -e "channel\tShow current or change channel to use different UnrealEditor version."
    echo ""
    echo "SUPPORTED BUILD OPTIONS"
    echo "  CrashReportClient"
    echo "  ShaderCompileWorker"
    echo "  UnrealLightmass"
    echo "  InterchangeWorker"
    echo "  UnrealPak"
    echo "  UnrealEditor"
    echo ""
    echo "PRESET"
    echo "  StandardSet"
    echo "  AlternativeSet"
    echo "  DebugSet"
    echo ""
    echo "SEE ALSO"
    echo "https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Build/BatchFiles/Linux/README.md"
    echo ""
    echo "EXAMPLE"
    echo -e "$0 AlternativeSet\nBuild using with AlternativeSet preset\n"
    echo -e "$0 CrashReportClient ShaderCompileWorker UnrealLightmass UnrealEditor UnrealPak\nBuild with provided options\n"
    echo -e "$0 --clean StandardSet\nClean UnrealEditor build files and build StandardSet preset"
    exit 0
elif [ "$1" == "clean" -o "$1" == "--clean" ]; then
    shouldProjectClean=1
elif [ "$1" == "channel" -o "$1" == "--channel" ]; then
    if [ x"$UEPath" == x -o ! -d "$UEPath/.git" ]; then
        echo "unable to locate UnrealEditor. please provide absolute path." >&2
        exit 1
    elif [ ! -x "$UEPath/Setup.sh" ]; then
        echo "UnrealEngine directory structure does not seem here." >&2
        echo "$UEPath" >&2
        echo "before use this change channel function, you should execute this cript without any parameters once."
        exit 1
    fi

    cd "$UEPath"
    if [ $? -ne 0 ]; then
        exit 1
    fi
    git remote update
    git --no-pager branch -r | sed "s/origin\///g" | grep -v "dev" | grep -v "stag" | grep -v "test" | grep -v "HEAD"
    echo "current branch: $(git branch --show-current)"
    echo -n "new branch name: "
    read n
    if [ x"$n" == x ]; then
        echo "User abort." >&2
        exit 1
    elif [ "$(git branch --show-current)" == "$n" ]; then
        echo "current branch and provided branch are identical" >&2
        exit 1
    else
        echo -e "\e[33mWarning\e[m: If you want to change UnrealEditor branch, you should rebuild UnrealEditor changes effect. This action can not be undo."
        echo -n "Are you sure continue this action? (y/N) > "
        read n
        if [ "$n" == "y" -o "$n" == "Y" ]; then
            echo "" > /dev/null
        else
            echo "User abort."
            exit 1
        fi

        git checkout -t origin/$n
        if [ $? -ne 0 ]; then
            echo "unable to change branch $n."
        else
            echo "successfully to change branch $n. you will need to execute this script again to building UnrealEditor."
        fi
        exit $?
    fi
fi

echo "Checking dependency..."
git --version
clang --version
cmake --version

if [ x"$UEPath" == x -o ! -d "$UEPath/.git" ]; then
    echo "unable to locate UnrealEditor. please provide absolute path." >&2
    exit 1
elif [ ! -x "$UEPath/Setup.sh" ]; then
    echo "UnrealEngine directory structure does not seem here." >&2
    echo "$UEPath" >&2
    echo -n "Would you like init UnrealEngine in provided path? (y/N) > "
    read n
    if [ "$n" == "Y" -o "$n" == "y" ]; then
        echo "You will need to your github account to locate UnrealEngine private repository."
        git clone https://github.com/EpicGames/UnrealEngine.git
        if [ $? -ne 0 ]; then
            exit 1
        fi
        echo "You can change default branch channel"
        echo 'To change branch channel: `git checkout -t origin/<branch>`'
    else
        echo "unable to locate UnrealEditor directory. no such file or directory." >&2
        exit 1
    fi
fi

echo "Current system infomations..."
df -h

cd "$UEPath"
if [ $? -ne 0 ]; then
    exit 1
fi
git remote update
if [ -n "$(git status --porcelain)" ]; then
    git status
    echo -e "\e[33mWarning! Possible conflict\e[m: You have uncommitted changes. please stage or commit them."
    echo 'If you want revert changes: `git restore <path>`'
    git diff
fi
echo -en "Would you like to continue?\nthis action can not be undo (y/N) > "
read n
if [ "$n" == "y" -o "$n" == "Y" ]; then
    echo "" > /dev/null
else
    echo "User abort." >&2
    exit 1
fi

echo "Updating repository..."

git pull origin $(git branch --show-current)
if [ $? -ne 0 ]; then
    echo "unable to update UnrealEngine repository. try again later." >&2
    exit 1
fi

echo "Generating project files..."

/bin/bash "$UEPath/Setup.sh"
if [ $? -ne 0 ]; then
    exit 1
fi

/bin/bash "$UEPath/GenerateProjectFiles.sh"
if [ $? -ne 0 ]; then
    exit 1
fi

if [ $shouldProjectClean -eq 1 ]; then
    echo "Invalidating UnrealEditor build caches and object files... Please wait."
    make UnrealEditor ARGS="-clean"
fi

if [ $shouldProjectClean -eq 0 ]; then
    if [ "$1" == "StandardSet" ]; then
        echo "Building StandardSet. See manual."
        make
    elif [ "$1" == "AlternativeSet" ]; then
        echo "Building AlternativeSet. See manual."
        make CrashReportClient ShaderCompileWorker UnrealLightmass InterchangeWorker UnrealPak UnrealEditor
    elif [ "$1" == "DebugSet" ]; then
        echo "Building DebugSet. See manual."
        make UnrealEditor-Linux-Debug
    else
        echo "Building $@. Please wait."
        make $@
    fi
else
    if [ "$2" == "StandardSet" ]; then
        echo "Building StandardSet. See manual."
        make
    elif [ "$2" == "AlternativeSet" ]; then
        echo "Building AlternativeSet. See manual."
        make CrashReportClient ShaderCompileWorker UnrealLightmass InterchangeWorker UnrealPak UnrealEditor
    elif [ "$2" == "DebugSet" ]; then
        echo "Building DebugSet. See manual."
        make UnrealEditor-Linux-Debug
    else
        echo "Building ${@:2}. Please wait."
        make ${@:2}
    fi
fi

