#!/bin/bash

target_path=/usr/share/applications/chromium.desktop
alt_target_path=/usr/share/applications/chromium-browser.desktop

if ! [ -r $target_path ]; then
    echo "changing target_path $target_path to $alt_target_path."
    echo "reason: $target_path no such file or directory."
    if ! [ -r $alt_target_path ]; then
        echo "no such file or directory: $target_path and $alt_target_path"
        exit 1
    fi
    target_path=$alt_target_path
fi

lsattr -l $target_path | grep Immutable &> /dev/null
if [ $? -ne 0 ]; then
    if [ -w $target_path ]; then
        sed -i 's/^MimeType/\# MimeType/' $target_path
        if [ $? -eq 0 ]; then
            update-desktop-database
        else
            echo "$target_path: requirements already satisfied"
        fi
    else
        echo "error: unable to write $target_path. Access denied." >&2
        exit 1
    fi
else
    echo "error: unable to write $target_path. Immutable flags enabled." >&2
    exit 1
fi

