#!/bin/bash

errorCount=0

which aptitude &> /dev/null
if [ $? == 0 ]; then
    sudo aptitude safe-upgrade
    if [ $? != 0 ]; then
        errorCount=$((errorCount+1))
    fi
fi

which pip3 &> /dev/null
if [ $? == 0 ]; then
    pip3 list --format=freeze | awk -F"==" '{print $1}' | xargs -i pip3 install -U {}
    if [ $? != 0 ]; then
        if [ $LANG == "ko_KR.UTF-8" ]; then
            echo "pip3 을 업데이트 하는 도중 에러가 발생하였습니다. "
        else
            echo "An error occured when updating pip3."
        fi
        errorCount=$((errorCount+1))
    fi
fi

which pip3.exe &> /dev/null
if [ $? == 0 ]; then
    pip3.exe list --format=freeze | awk -F"==" '{print $1}' | xargs -i pip3.exe install -U {}
    if [ $? != 0 ]; then
        if [ $LANG == "ko_KR.UTF-8" ]; then
            echo "pip3.exe 을 업데이트 하는 도중 에러가 발생하였습니다. "
        else
            echo "An error occured when updating pip3.exe."
        fi
        errorCount=$((errorCount+1))
    fi
fi

do-release-upgrade
if [ $? != 0 ]; then
    errorCount=$((errorCount+1))
fi

which wsl.exe > /dev/null 2>&1
if [ $? == 0 ]; then
    wsl.exe --update
    if [ $? != 0 ]; then
        errorCount=$((errorCount+1))
    fi
fi

which pip3 &> /dev/null
if [ $? == 0 ]; then
    pip3 cache purge
    if [ $? != 0 ]; then
        errorCount=$((errorCount+1))
    fi
fi

which winget.exe &> /dev/null
if [ $? == 0 ]; then
    cmd.exe "/c" "winget.exe upgrade --all"
    if [ $? != 0 ]; then
        errorCount=$((errorCount+1))
    fi
    echo -e "\e[m"
fi

if [ -x ~/.local/bin/gitVI_update ]; then
    ~/.local/bin/gitVI_update
    if [ $? != 0 ]; then
        errorCount=$((errorCount+1))
    fi
fi

which zsh &> /dev/null
if [ $? == 0 ]; then
    /bin/zsh -c "source ~/.zshrc; which omz > /dev/null 2>&1"
    if [ $? == 0 ]; then
        /bin/zsh -c "source ~/.zshrc; omz update"
        echo $!
        if [ $? != 0 ]; then
            errorCount=$((errorCount+1))
        fi
    fi
fi

if [ ! -x /mnt/c/Windows/System32/cmd.exe ]; then
    which flutter &> /dev/null
    if [ $? == 0 ]; then
        flutter upgrade
        flutter doctor
    fi
else
    where.exe flutter &> /dev/null
    if [ $? == 0 ]; then
        cmd.exe "/c" "flutter upgrade"
        cmd.exe "/c" "flutter doctor"
    fi
fi

if [ $errorCount -gt 0 ]; then
    exit 1
else
    exit 0
fi
