#!/bin/bash

which aptitude &>/dev/null
if [ $? == 0 ]; then
  sudo aptitude safe-upgrade
fi

if [ "$USE_FULL_UPGRADE" == "true" ]; then
  which pip3 &>/dev/null
  if [ $? == 0 ]; then
    python3 -m pip config set global.break-system-packages true
    if [ $? -eq 0 ]; then
      pip3 list --format=freeze | awk -F"==" '{print $1}' | xargs -i pip3 install -U {}
    fi
  fi

  which pip3.exe &>/dev/null
  if [ $? == 0 ]; then
    pip3.exe list --format=freeze | awk -F"==" '{print $1}' | xargs -i pip3.exe install -U {}
    python.exe -m pip install -U pip
  fi
  echo -e "\n"
fi

which p4 &> /dev/null
if [ $? -eq 0 ]; then
    relnotes="https://help.perforce.com/helix-core/release-notes/current/relnotes.txt"
    echo 'Perforce (P4) release list.'
    echo "--- $(/usr/bin/date '+%Y') ---"
    curl -fsSL $relnotes | grep "Major new functionality in $(/usr/bin/date '+%Y')" | sed "s/Major new functionality in //"
    echo "--- $(/usr/bin/date '+%Y' -d '1 year ago') ---"
    curl -fsSL $relnotes | grep "Major new functionality in $(/usr/bin/date '+%Y' -d '1 year ago')" | sed "s/Major new functionality in //"
    echo -en '\nCurrent installed '
    p4 -V | tail -1 | sed "s/Rev. P4\/LINUX26X86_64\///"
    echo 'Please download P4 in below link, if new release available.'
    echo -e "\thttps://www.perforce.com/downloads/helix-command-line-client-p4"
fi

which nvim &> /dev/null
if [ $? -eq 0 ]; then
    nvim --version > /dev/null
    if [ $? -ne 0 ]; then
        echo 'neovim package was corrupted.'
        echo 'Please re-install neovim in below link.'
        echo -e "\thttps://github.com/neovim/neovim/releases/latest"
    else
        local=$(nvim --version | grep NVIM | awk '{ print $2 }')
        release=$(curl -fsSL https://github.com/neovim/neovim/releases/latest | grep '<title>' | awk '{ print $3 }')
        if [ "$local" != "$release" ]; then
            echo 'Please download neovim in below link.'
            echo -e "\thttps://github.com/neovim/neovim/releases/latest"
        else
            echo "Neovim is up to date ($local)."
        fi
    fi
fi

which wsl.exe &>/dev/null
if [ $? == 0 ]; then
  wsl.exe --status
  wsl.exe --version
  if [ $LANG == "ko_KR.UTF-8" ]; then
    echo 'WSL 업데이트를 확인하려면 `wsl.exe --update --web-download` 코드를 실행하세요.'
  else
    echo 'Please enter `wsl.exe --update --web-download` command if you wanna check WSL updates.'
  fi
fi

which pip3 &>/dev/null
if [ $? == 0 ]; then
  pip3 cache purge
fi

which winget.exe &>/dev/null
if [ $? == 0 ]; then
  #     cmd.exe "/c" "winget.exe upgrade --all"
  cmd.exe "/c" "winget.exe upgrade"
  echo -e "\e[m"
fi

if [ -x ~/.local/bin/gitVI_update ]; then
  ~/.local/bin/gitVI_update
fi

which juliaup &> /dev/null
if [ $? -eq 0 ]; then
    juliaup update
fi

which zsh &>/dev/null
if [ $? == 0 ]; then
  /bin/zsh -c "source ~/.zshrc; which omz > /dev/null 2>&1"
  if [ $? == 0 ]; then
    /bin/zsh -c "source ~/.zshrc; omz update" &
    targetPID=$!
    for (( i=0 ; i<=10 ; i++ )); do
        ps | grep $targetPID &> /dev/null
        if [ $? -ne 0 ]; then
            break
        fi
        sleep 1
    done
    ps | grep $targetPID &> /dev/null
    if [ $? -eq 0 ]; then
        kill $targetPID &> /dev/null
    fi
  fi
fi

if [ ! -x /mnt/c/Windows/System32/cmd.exe ]; then
  which flutter &>/dev/null
  if [ $? == 0 ]; then
    flutter upgrade
    flutter doctor
  fi
else
  where.exe flutter &>/dev/null
  if [ $? == 0 ]; then
    cmd.exe "/c" "flutter upgrade"
    cmd.exe "/c" "flutter doctor"
  fi
fi

which flatpak &> /dev/null
if [ $? -eq 0 ]; then
    flatpak update
fi

