#!/bin/bash

if [ "$(id -u)" = "0" ]; then
    if [ $LANG == "ko_KR.UTF-8" ]; then
        echo -e "\e[31m오류\e[m: 이 작업은 $USER에게는 금지되어 있습니다. "
    else
        echo -e "\e[31mERR\e[m: This script does not allowed $USER"
    fi
    exit 1
fi

if [ $LANG == "ko_KR.UTF-8" ]; then
    echo -e "$USER님 FactoryReset에 오신 것을 환영합니다! 이 작업은 당신의 홈 폴더를 초기화할 것입니다. "
else
    echo -e "Welcome to FactoryReset $USER! This prograss will resetting your home folder."
fi
if [ $LANG == "ko_KR.UTF-8" ]; then
    echo -e "정말로 \e[0;1m$HOME\e[m 의 파일들을 삭제하겠습니까? 이 파일들은 즉시 삭제 됩니다. "
    echo -en "\e[33m주의\e[m: 이 작업은 취소할 수 없습니다. 계속하시겠습니까? (예/아니요) > "
else
    echo -e "Are you sure delete \e[0;1m$HOME\e[m files? This files will be deleted immediately. "
    echo -en "\e[33mCAUTION\e[m: You can not undo this operation. Do you want to continue? (y/N) > "
fi

read inputKey
if [ "${inputKey}" = "Y" -o  "${inputKey}" = "y" -o "${inputKey}" = "예" ]; then
    if [ $LANG == "ko_KR.UTF-8" ]; then
        echo -e "계속하려면 $USER 암호를 입력하세요. "
    else
        echo -e "Please enter $USER password to continue."
    fi
    su -c 'cd ~ && rm -rf * && rm -rf .*' - $USER
    if [ $? == 0 ]; then
        if [ $LANG == "ko_KR.UTF-8" ]; then
            echo -e "\e[34m성공\e[m: 성공적으로 홈 폴더 파일을 삭제했습니다. \"$HOME\" 폴더를 확인하여 주십시오."
            echo -e "$USER의 비밀번호를 공지된 규칙에 맞게 초기화해 주세요. "
        else
            echo -e "\e[34mOK\e[m: Successfully deleted private files. check your \"$HOME\"."
            echo -e "Please reset $USER password according to the announced rules."
        fi
        passwd
        exit 0
    else
        if [ $LANG == "ko_KR.UTF-8" ]; then
            echo -e "\e[31m오류\e[m: 홈 폴더 파일을 삭제하지 못했습니다. 계정 인증에 실패하였습니다. "
        else
            echo -e "\e[31mERR\e[m: Failed to delete the home folder files. Account authentication failed."
        fi
        exit 1
    fi
else
    if [ $LANG == "ko_KR.UTF-8" ]; then
        echo -e "\e[31m오류\e[m: 사용자가 FactoryReset 작업을 중단했습니다. "
    else
        echo -e "\e[31mERR\e[m: User abort FactoryReset progress. "
    fi
    exit 1
fi

