#!/bin/bash

which flutter &> /dev/null
if [ $? != 0 ]; then
    exit 1
fi

which wsl.exe &> /dev/null
if [ $? == 0 ]; then
    /mnt/c/Windows/System32/cmd.exe "/c" "flutter $@"
else
    flutter $@
fi
