#!/bin/bash

function daemon-reload() {
    if [ $UID -ne 0 ]; then
        sudo systemctl daemon-reload
        sudo systemctl restart mbpfan
    else
        systemctl daemon-reload
        systemctl restart mbpfan
    fi
}

if ! [ -r /etc/mbpfan.conf ]; then
    echo 'error: unable to find mbpfan config file.' >&2
    exit 1
fi

if ! [ -d /etc/mbpfan.d ]; then
    if [ $(file /etc/mbpfan.conf | grep -c 'symbolic') -gt 0 ]; then
        echo 'error: unable to find mbpfan profile directory.' >&2
        exit 1
    fi
    if [ $UID -ne 0 ]; then
        sudo mkdir /etc/mbpfan.d
        sudo mv /etc/mbpfan.conf /etc/mbpfan.d/default
        sudo ln -s /etc/mbpfan.d/default /etc/mbpfan.conf
    else
        mkdir /etc/mbpfan.d
        mv /etc/mbpfan.conf /etc/mbpfan.d/default
        ln -s /etc/mbpfan.d/default /etc/mbpfan.conf
    fi
    daemon-reload
fi

if [ $# -eq 0 -o "$1" == "status" ]; then
    echo "current_profile = $(basename `readlink /etc/mbpfan.conf`)"
    cat /etc/mbpfan.conf | grep '^m.._fan._speed =' | awk -F '#' '{ print $1 }'
    cat /etc/mbpfan.conf | grep 'temp =' | awk -F '#' '{ print $1 }'
elif [ "$1" == "ls" -o "$1" == "list" ]; then
    ls /etc/mbpfan.d
elif [ $# -eq 2 -a "$1" == "new" ]; then
    if [ $# -eq 2 ]; then
        if [ -r /etc/mbpfan.d/$2 ]; then
            echo "error: $2 profile already exist." >&2
            exit 1
        fi

        filename=/tmp/mbpfan-$(date +'%Y-%m-%d_%H:%M:%S')-$2
        cp /etc/mbpfan.d/default $filename
        vi $filename
        cmp -s /etc/mbpfan.d/default $filename
        if [ $? -eq 0 ]; then
            echo "Aborting create $2 profile due to identical default profile." >&2
        else
            if [ $UID -ne 0 ]; then
                sudo mv $filename /etc/mbpfan.d/$2
            else
                mv $filename /etc/mbpfan.d/$2
            fi
            echo "please re-run this script to apply $2 profile."
        fi
    elif [ $# -eq 3 ]; then
        if ! [ -r /etc/mbpfan.d/$2 ]; then
            echo "error: no such profile: $2" >&2
            exit 1
        elif [ -r /etc/mbpfan.d/$3 ]; then
            echo "error: $3 profile already exist." >&2
            exit 1
        fi

        filename=/tmp/mbpfan-$(date +'%Y-%m-%d_%H:%M:%S')-$3
        cp /etc/mbpfan.d/$2 $filename
        vi $filename
        cmp -s /etc/mbpfan.d/$2 $filename
        if [ $? -eq 0 ]; then
            echo "Aborting create $3 profile due to identical $2 profile." >&2
        else
            if [ $UID -ne 0 ]; then
                sudo mv $filename /etc/mbpfan.d/$3
            else
                mv $filename /etc/mbpfan.d/$3
            fi
            echo "please re-run this script to apply $3 profile."
        fi
    fi
elif [ "$1" == "edit" ]; then
    if [ $# -eq 1 ]; then
        filename=/tmp/mbpfan-$(date +'%Y-%m-%d_%H:%M:%S')-$(basename `readlink /etc/mbpfan.conf`)
        cp /etc/mbpfan.d/$(basename `readlink /etc/mbpfan.conf`) $filename
        vi $filename
        cmp -s /etc/mbpfan.d/$(basename `readlink /etc/mbpfan.conf`) $filename
        if [ $? -eq 0 ]; then
            echo "Aborting edit $(basename `readlink /etc/mbpfan.conf`) profile due to identical." >&2
        else
            if [ $UID -ne 0 ]; then
                sudo mv -f $filename /etc/mbpfan.d/$(basename `readlink /etc/mbpfan.conf`)
            else
                mv -f $filename /etc/mbpfan.d/$(basename `readlink /etc/mbpfan.conf`)
            fi
            daemon-reload
        fi
    else
        target=("$@")
        for i in "${!target[@]}"; do
            if [ "${target[$i]}" == "edit" ]; then
                continue
            fi
            if ! [ -r /etc/mbpfan.d/${target[$i]} ]; then
                echo "error: no such profile: ${target[$i]}. Skipping" >&2
                continue
            fi

            filename=/tmp/mbpfan-$(date +'%Y-%m-%d_%H:%M:%S')-${target[$i]}
            cp /etc/mbpfan.d/${target[$i]} $filename
            vi $filename
            cmp -s /etc/mbpfan.d/${target[$i]} $filename
            if [ $? -eq 0 ]; then
                echo "Aborting edit ${target[$i]} profile due to identical." >&2
            else
                if [ $UID -ne 0 ]; then
                    sudo mv -f $filename /etc/mbpfan.d/${target[$i]}
                else
                    mv -f $filename /etc/mbpfan.d/${target[$i]}
                fi
            fi
        done
    fi
elif [ $# -eq 2 -a "$1" == "set" ]; then
    if [ -r /etc/mbpfan.d/$2 ]; then
        prev_profile=$(basename `readlink /etc/mbpfan.conf`)
        if [ "$prev_profile" == "$2" ]; then
            echo "error: current and provided profile are identical" >&2
            exit 1
        fi

        if [ $UID -ne 0 ]; then
            sudo ln -sf /etc/mbpfan.d/$2 /etc/mbpfan.conf
        else
            ln -sf /etc/mbpfan.d/$2 /etc/mbpfan.conf
        fi
        daemon-reload
        echo "profile changed $prev_profile to $2"
    else
        echo "error: no such profile: $2" >&2
        exit 1
    fi
elif [ "$1" == "remove" -o "$1" == "rm" ]; then
    prev_profile=$(basename `readlink /etc/mbpfan.conf`)
    target=("$@")

    for i in "${!target[@]}"; do
        if [ "${target[$i]}" == "rm" -o "${target[$i]}" == "remove" ]; then
            continue
        fi
        if ! [ -r /etc/mbpfan.d/${target[$i]} ]; then
            echo "error: no such profile: ${target[$i]}. Skipping" >&2
            continue
        fi

        if [ "$prev_profile" == "${target[$i]}" ]; then
            echo "error: unable to remove provided profile in currently use. Skipping" >&2
        else
            if [ $UID -ne 0 ]; then
                sudo rm /etc/mbpfan.d/${target[$i]}
            else
                rm /etc/mbpfan.d/${target[$i]}
            fi
        fi
    done
elif [ "$1" == "help" ]; then
    echo 'usage: mbpfan [option|profile]'
    echo -e '\nOPTIONS'
    echo -e "  list\t\t\t\tshow available profiles."
    echo -e "   set <profile>\t\tupdate new profile for mbpfan."
    echo -e "   new [source] <name>\t\tcreate new profile."
    echo -e "  edit [name ...]\t\tedit specific or current profile."
    echo -e "remove <name ...>\t\tdelete specific profile."
    echo -e "  help\t\t\t\tshow this help."
    echo -e '\nAVAILABLE PROFILES'
    ls /etc/mbpfan.d
else
    echo "unknown options: $@" >&2
    exit 1
fi
