#!/bin/bash

function check-permission() {
    if [ $UID -ne 0 ]; then
        echo "$USER is not in super-user group. Are you root?" >&2
        logger --tag mbpfan --priority auth.err "access denied. $USER does not have any super-user permissions."
        exit 1
    fi
}

function daemon-reload() {
    logger --tag mbpfan --priority daemon.notice '`daemon-reload` called. reloading /etc/mbpfan.conf...'
    logger --tag mbpfan --priority daemon.debug 'checking symbolic link for /etc/mbpfan.conf'
    if [ -r "$(readlink /etc/mbpfan.conf)" ]; then
        logger --tag mbpfan --priority daemon.debug "successfully verified symbolic link /etc/mbpfan.conf <--> /etc/mbpfan.d/$(basename `readlink /etc/mbpfan.conf`)"
        logger --tag mbpfan --priority daemon.debug "loaded profile name: $(basename `readlink /etc/mbpfan.conf`)"
        systemctl daemon-reload
        cat /etc/mbpfan.conf | sed 's/#.*//' | sed '/^$/d' | logger --tag mbpfan --priority daemon.debug
        systemctl restart mbpfan
        if [ $? -eq 0 ]; then
            logger --tag mbpfan --priority daemon.debug 'successfully restarted mbpfan daemon'
            logger --tag mbpfan --priority daemon.notice 'If the current fan speed is greater than the maximum fan speed, it may take longer for the changes to take effect.'
        else
            logger --tag mbpfan --priority daemon.err 'failed to restart mbpfan daemon. try again later.'
        fi
    else
        logger --tag mbpfan --priority daemon.alert 'unable to verify symbolic link /etc/mbpfan.conf <--> <UNKNOWN>'
        logger --tag mbpfan --priority daemon.notice "unable to following symbolic link to <UNKNOWN>. <UNKNOWN> is not correct file or directory name."
        if [ -d /etc/mbpfan.d -a -f /etc/mbpfan.d/default ]; then
            logger --tag mbpfan --priority daemon.notice 'attempt to reassign symbolic link /etc/mbpfan.conf <--> /etc/mbpfan.d/default'
            ln -sf /etc/mbpfan.d/default /etc/mbpfan.conf
            if [ $? -eq 0 ]; then
                logger --tag mbpfan --priority daemon.debug 'successfully reassigned symbolic link /etc/mbpfan.conf <--> /etc/mbpfan.d/default'
                logger --tag mbpfan --priority daemon.info 'restarting `daemon-reload` function'
                daemon-reload
            else
                logger --tag mbpfan --priority daemon.crit 'unable to reassign symbolic link /etc/mbpfan.conf <--> /etc/mbpfan.d/default. Exiting!'
                logger --tag mbpfan --priority daemon.alert 'exiting `mbpfan` script due to unrecoverable error detected. all unsaved data will be lost.'
                exit 1
            fi
        elif [ -d /etc/mbpfan.d ]; then
            logger --tag mbpfan --priority daemon.crit 'unable to reassign symbolic link /etc/mbpfan.conf <--> /etc/mbpfan.d/default. no such default profile. Exiting!'
            logger --tag mbpfan --priority daemon.alert 'exiting `mbpfan` script due to unrecoverable error detected. all unsaved data will be lost.'
            exit 1
        else
            logger --tag mbpfan --priority daemon.crit "unable to locate /etc/mbpfan.d directory. Exiting!"
            logger --tag mbpfan --priority daemon.alert 'exiting `mbpfan` script due to unrecoverable error detected. all unsaved data will be lost.'
            exit 1
        fi
    fi
}

if ! [ -r /etc/mbpfan.conf ]; then
    echo 'error: unable to find mbpfan config file.' >&2
    logger --tag mbpfan --priority syslog.crit 'unable to find /etc/mbpfan.conf. no such file or directory.'
    exit 1
fi

if ! [ -d /etc/mbpfan.d ]; then
    if [ $(file /etc/mbpfan.conf | grep -c 'symbolic') -gt 0 ]; then
        logger --tag mbpfan --priority syslog.crit 'unable to find /etc/mbpfan.d. no such file or directory.'
        logger --tag mbpfan --priority syslog.crit 'unable to find /etc/mbpfan.conf. unlinked symbolic file detected.'
        echo 'error: unable to find mbpfan profile directory.' >&2
        exit 1
    fi
    mkdir /etc/mbpfan.d
    mv /etc/mbpfan.conf /etc/mbpfan.d/$(basename `readlink /etc/mbpfan.conf`)
    ln -s /etc/mbpfan.d/$(basename `readlink /etc/mbpfan.conf`) /etc/mbpfan.conf
    logger --tag mbpfan --priority daemon.info 'successfully created config directory structures and linked /etc/mbpfan.conf <--> /etc/mbpfan.d/default'
    daemon-reload
fi

if [ $# -eq 0 -o "$1" == "status" ]; then
    echo "current_profile = $(basename `readlink /etc/mbpfan.conf`)"

    target_inode=$(stat -c '%i' /etc/mbpfan.d/$(basename `readlink /etc/mbpfan.conf`))
    match_inode=0
    target=($(ls -li /etc/mbpfan.d | grep -v $(basename `readlink /etc/mbpfan.conf`) | grep -v 'total' | awk '{ print $1 }'))
    for i in "${!target[@]}"; do
        if [ $target_inode -eq ${target[$i]} ]; then
            match_inode=${target[$i]}
        fi
    done
    if [ $match_inode -ne 0 ]; then
        echo "inherited = $(ls -li /etc/mbpfan.d | grep -v 'total' | grep -v $(basename `readlink /etc/mbpfan.conf`) | grep $match_inode | awk '{ print $10 }' | tr '\n' ' ')"
    fi

    cat /etc/mbpfan.conf | grep '^m.._fan._speed =' | awk -F '#' '{ print $1 }' | sed 's/$/\t(±0.35%)/'
    cat /etc/mbpfan.conf | grep 'temp =' | awk -F '#' '{ print $1 }'
    sensors -u applesmc-isa-0300 | grep fan | grep input | cut -d. -f1 | sed 's/^  /cnt_/' | sed 's/: / = /' | sed 's/input/speed/'
    sensors -u coretemp-isa-0000 | grep temp._input | cut -d. -f1 | sed 's/^  /cnt_cpu_/' | sed 's/: / = /' | sed 's/_input//'

    current_mode=$(cat /sys/devices/system/cpu/intel_pstate/no_turbo)
    if [ $current_mode -eq 0 ]; then
        echo "intel_turbo_boost = $(cat /sys/devices/system/cpu/intel_pstate/turbo_pct)"
    else
        echo -e "intel_turbo_boost = 0\t\t(disabled)"
    fi
elif [ $# -ge 2 -a "$1" == "show" ]; then
    if ! [ -r /etc/mbpfan.d/$2 ]; then
        echo "error: no such profile: $2" >&2
        exit 1
    fi

    target=("$@")
    for i in "${!target[@]}"; do
        if [ "${target[$i]}" == "show" ]; then
            continue
        fi
        if ! [ -r /etc/mbpfan.d/${target[$i]} ]; then
            echo "error: no such profile: ${target[$i]}. Skipping" >&2
            continue
        fi
        echo "profile_name = ${target[$i]}"

        target_inode=$(stat -c '%i' /etc/mbpfan.d/${target[$i]})
        match_inode=0
        configs=($(ls -li /etc/mbpfan.d | grep -v ${target[$i]} | grep -v 'total' | awk '{ print $1 }'))
        for j in "${!configs[@]}"; do
            if [ $target_inode -eq ${configs[$j]} ]; then
                match_inode=${configs[$j]}
            fi
        done
        if [ $match_inode -ne 0 ]; then
            echo "inherited = $(ls -li /etc/mbpfan.d | grep -v 'total' | grep -v ${target[$i]} | grep $match_inode | awk '{ print $10 }' | tr '\n' ' ')"
        fi

        cat /etc/mbpfan.d/${target[$i]} | grep '^m.._fan._speed =' | awk -F '#' '{ print $1 }' | sed 's/$/\t(±0.35%)/'
        cat /etc/mbpfan.d/${target[$i]} | grep 'temp =' | awk -F '#' '{ print $1 }'
    done
elif [ "$1" == "get" ] && [ $# -ge 2 -a $# -le 3 ]; then
    if [ "$2" == "name" ]; then
        echo "$(basename `readlink /etc/mbpfan.conf`)"
    elif [ "$2" == "speed" ]; then
        if [ $# -eq 2 ]; then
            cat /etc/mbpfan.d/$(basename `readlink /etc/mbpfan.conf`) | grep '^m.._fan._speed =' | awk -F '#' '{ print $1 }'
            sensors -u applesmc-isa-0300 | grep fan | grep input | cut -d. -f1 | sed 's/^  /cnt_/' | sed 's/: / = /' | sed 's/input/speed/'
        else
            if [ "$3" == 'min' ]; then
                cat /etc/mbpfan.d/$(basename `readlink /etc/mbpfan.conf`) | grep '^min_fan._speed =' | awk -F '#' '{ print $1 }'
            elif [ "$3" == 'max' ]; then
                cat /etc/mbpfan.d/$(basename `readlink /etc/mbpfan.conf`) | grep '^max_fan._speed =' | awk -F '#' '{ print $1 }'
            elif [ "$3" == 'cnt' ]; then
                sensors -u applesmc-isa-0300 | grep fan | grep input | cut -d. -f1 | sed 's/^  /cnt_/' | sed 's/: / = /' | sed 's/input/speed/'
            else
                echo "unknown options: $@" >&2
                exit 1
            fi
        fi
    elif [ "$2" == "temp" ]; then
        if [ $# -eq 2 ]; then
            cat /etc/mbpfan.d/$(basename `readlink /etc/mbpfan.conf`) | grep 'temp =' | awk -F '#' '{ print $1 }'
            sensors -u coretemp-isa-0000 | grep temp._input | cut -d. -f1 | sed 's/^  /cnt_cpu_/' | sed 's/: / = /' | sed 's/_input//'
        else
            if [ "$3" == 'low' ]; then
                cat /etc/mbpfan.d/$(basename `readlink /etc/mbpfan.conf`) | grep 'low_temp =' | awk -F '#' '{ print $1 }'
            elif [ "$3" == 'high' ]; then
                cat /etc/mbpfan.d/$(basename `readlink /etc/mbpfan.conf`) | grep 'high_temp =' | awk -F '#' '{ print $1 }'
            elif [ "$3" == 'max' ]; then
                cat /etc/mbpfan.d/$(basename `readlink /etc/mbpfan.conf`) | grep 'max_temp =' | awk -F '#' '{ print $1 }'
            elif [ "$3" == 'cnt' ]; then
                sensors -u coretemp-isa-0000 | grep temp._input | cut -d. -f1 | sed 's/^  /cnt_cpu_/' | sed 's/: / = /' | sed 's/_input//'
            else
                echo "unknown options: $@" >&2
                exit 1
            fi
        fi
    else
        echo "unknown options: $@" >&2
        exit 1
    fi
elif [ "$1" == "ls" -o "$1" == "list" ]; then
    ls /etc/mbpfan.d | sed "s/$(basename `readlink /etc/mbpfan.conf`)/$(basename `readlink /etc/mbpfan.conf`)*/"
elif [ "$1" == "new" ]; then
    if [ $# -eq 2 ]; then
        if [ -r /etc/mbpfan.d/$2 ]; then
            echo "error: $2 profile already exist." >&2
            exit 1
        fi

        check-permission
        filename=/tmp/mbpfan-$(date +'%Y-%m-%d_%H:%M:%S')-$2
        cp /etc/mbpfan.d/$(basename `readlink /etc/mbpfan.conf`) $filename
        vi $filename
        cmp -s /etc/mbpfan.d/$(basename `readlink /etc/mbpfan.conf`) $filename
        if [ $? -eq 0 ]; then
            echo "Aborting create $2 profile due to identical $(basename `readlink /etc/mbpfan.conf`) profile." >&2
            rm $filename
        else
            mv $filename /etc/mbpfan.d/$2
            chown root:root /etc/mbpfan.d/$2
            logger --tag mbpfan --priority user.info "successfully created $2 profile with $(basename `readlink /etc/mbpfan.conf`)"
            echo "please re-run this script to apply $2 profile."
        fi
    elif [ $# -eq 3 ]; then
        if ! [ -r /etc/mbpfan.d/$2 ]; then
            echo "error: no such profile: $2" >&2
            exit 1
        elif [ -r /etc/mbpfan.d/$3 ]; then
            echo "error: $3 profile already exist." >&2
            exit 1
        fi

        check-permission
        filename=/tmp/mbpfan-$(date +'%Y-%m-%d_%H:%M:%S')-$3
        cp /etc/mbpfan.d/$2 $filename
        vi $filename
        cmp -s /etc/mbpfan.d/$2 $filename
        if [ $? -eq 0 ]; then
            echo "Aborting create $3 profile due to identical $2 profile." >&2
            rm $filename
        else
            mv $filename /etc/mbpfan.d/$3
            chown root:root /etc/mbpfan.d/$3
            logger --tag mbpfan --priority user.info "successfully created $3 profile with $2"
            echo "please re-run this script to apply $3 profile."
        fi
    fi
elif [ "$1" == "lnk" -o "$1" == "link" ]; then
    if [ $# -eq 2 ]; then
        if [ -r /etc/mbpfan.d/$2 ]; then
            echo "error: $2 profile already exist." >&2
            exit 1
        fi

        check-permission
        ln /etc/mbpfan.d/$(basename `readlink /etc/mbpfan.conf`) /etc/mbpfan.d/$2
        chown root:root /etc/mbpfan.d/$2
        logger --tag mbpfan --priority user.info "successfully linked $2 profile with $(basename `readlink /etc/mbpfan.conf`)"
        echo "please re-run this script to apply $2 profile."
    elif [ $# -eq 3 ]; then
        if ! [ -r /etc/mbpfan.d/$2 ]; then
            echo "error: no such profile: $2" >&2
            exit 1
        elif [ -r /etc/mbpfan.d/$3 ]; then
            echo "error: $3 profile already exist." >&2
            exit 1
        fi

        check-permission
        ln /etc/mbpfan.d/$2 /etc/mbpfan.d/$3
        chown root:root /etc/mbpfan.d/$3
        logger --tag mbpfan --priority user.info "successfully linked $3 profile with $2"
        echo "please re-run this script to apply $3 profile."
    fi
elif [ "$1" == "edit" ]; then
    if [ $# -eq 1 ]; then
        check-permission
        filename=/tmp/mbpfan-$(date +'%Y-%m-%d_%H:%M:%S')-$(basename `readlink /etc/mbpfan.conf`)
        cp /etc/mbpfan.d/$(basename `readlink /etc/mbpfan.conf`) $filename
        vi $filename
        cmp -s /etc/mbpfan.d/$(basename `readlink /etc/mbpfan.conf`) $filename
        if [ $? -eq 0 ]; then
            echo "Aborting edit $(basename `readlink /etc/mbpfan.conf`) profile due to identical." >&2
            rm $filename
        else
            diff /etc/mbpfan.d/$(basename `readlink /etc/mbpfan.conf`) $filename | logger --tag mbpfan --priority user.debug
            mv -f $filename /etc/mbpfan.d/$(basename `readlink /etc/mbpfan.conf`)
            logger --tag mbpfan --priority user.debug "currently using $(basename `readlink /etc/mbpfan.conf`) profile changed. reloading..."
            logger --tag mbpfan --priority user.info "successfully altered $(basename `readlink /etc/mbpfan.conf`) profile"
            daemon-reload
        fi
    else
        target=("$@")
        for i in "${!target[@]}"; do
            if [ "${target[$i]}" == "edit" ]; then
                continue
            fi
            if ! [ -r /etc/mbpfan.d/${target[$i]} ]; then
                echo "error: no such profile: ${target[$i]}. Skipping" >&2
                continue
            fi

            check-permission
            filename=/tmp/mbpfan-$(date +'%Y-%m-%d_%H:%M:%S')-${target[$i]}
            cp /etc/mbpfan.d/${target[$i]} $filename
            vi $filename
            cmp -s /etc/mbpfan.d/${target[$i]} $filename
            if [ $? -eq 0 ]; then
                echo "Aborting edit ${target[$i]} profile due to identical." >&2
                rm $filename
            else
                diff /etc/mbpfan.d/${target[$i]} $filename | logger --tag mbpfan --priority user.debug
                mv -f $filename /etc/mbpfan.d/${target[$i]}
                if [ "${target[$i]}" == "$(basename `readlink /etc/mbpfan.conf`)" ]; then
                    logger --tag mbpfan --priority user.debug "currently using $(basename `readlink /etc/mbpfan.conf`) profile changed. reloading..."
                    logger --tag mbpfan --priority user.info "successfully altered $(basename `readlink /etc/mbpfan.conf`) profile"
                    daemon-reload
                else
                    logger --tag mbpfan --priority user.info "successfully altered ${target[$i]} profile"
                fi
            fi
        done
    fi
elif [ "$1" == "set" ]; then
    if [ $# -eq 2 ]; then
        if [ -r /etc/mbpfan.d/$2 ]; then
            prev_profile=$(basename `readlink /etc/mbpfan.conf`)
            if [ "$prev_profile" == "$2" ]; then
                echo "error: current and provided profile are identical" >&2
                exit 1
            fi

            check-permission
            ln -sf /etc/mbpfan.d/$2 /etc/mbpfan.conf
            daemon-reload
            echo "successfully changed $prev_profile profile to $2"
            logger --tag mbpfan --priority daemon.debug "successfully reassigned /etc/mbpfan.conf <--> /etc/mbpfan.d/$2"
        else
            echo "error: no such profile: $2" >&2
            exit 1
        fi
    else
        prev_profile=$(basename `readlink /etc/mbpfan.conf`)
        if [ "$prev_profile" == "default" ]; then
            echo "error: current and $(basename `readlink /etc/mbpfan.conf`) profile are identical" >&2
            exit 1
        fi

        if [ -r /etc/mbpfan.d/default ]; then
            check-permission
            ln -sf /etc/mbpfan.d/default /etc/mbpfan.conf
            daemon-reload
            echo "successfully changed $prev_profile profile to default"
            logger --tag mbpfan --priority daemon.debug "successfully reassigned /etc/mbpfan.conf <--> /etc/mbpfan.d/default"
        else
            echo "unable to set profile to default. no such profile: default" >&2
            logger --tag mbpfan --priority user.err "unable to find default profile in /etc/mbpfan.d. no such file or directory"
            exit 1
        fi
    fi
elif [ "$1" == "rename" -o "$1" == "rn" ]; then
    if [ $# -eq 2 ]; then
        if [ -r /etc/mbpfan.d/$2 ]; then
            echo "error: $2 profile already exist." >&2
            exit 1
        fi

        check-permission
        prev_profile=$(basename `readlink /etc/mbpfan.conf`)
        mv /etc/mbpfan.d/$(basename `readlink /etc/mbpfan.conf`) /etc/mbpfan.d/$2
        ln -sf /etc/mbpfan.d/$2 /etc/mbpfan.conf
        daemon-reload
        echo "successfully renamed $prev_profile profile to $2"
        logger --tag mbpfan --priority user.info "successfully renamed $prev_profile profile to $2"
    else
        if ! [ -r /etc/mbpfan.d/$2 ]; then
            echo "error: no such profile: $2" >&2
            exit 1
        elif [ -r /etc/mbpfan.d/$3 ]; then
            echo "error: $3 profile already exist." >&2
            exit 1
        fi

        check-permission
        mv /etc/mbpfan.d/$2 /etc/mbpfan.d/$3
        logger --tag mbpfan --priority user.info "successfully renamed $2 profile to $3"
        echo "successfully renamed $2 profile to $3"
    fi
elif [ "$1" == "remove" -o "$1" == "rm" ]; then
    prev_profile=$(basename `readlink /etc/mbpfan.conf`)
    target=("$@")

    for i in "${!target[@]}"; do
        if [ "${target[$i]}" == "rm" -o "${target[$i]}" == "remove" ]; then
            continue
        fi
        if ! [ -r /etc/mbpfan.d/${target[$i]} ]; then
            echo "error: no such profile: ${target[$i]}. Skipping" >&2
            continue
        fi

        if [ "$prev_profile" == "${target[$i]}" ]; then
            echo "error: unable to remove provided profile in currently use. Skipping" >&2
            logger --tag mbpfan --priority user.err "unable to drop ${target[$i]} profile due to dependancy failure"
            exit 1
        else
            check-permission
            rm /etc/mbpfan.d/${target[$i]}
            logger --tag mbpfan --priority user.info "successfully drop ${target[$i]} profile"
            echo "successfully deleted ${target[$i]} profile"
        fi
    done
elif [ "$1" == "turbo" ]; then
    if [ $# -eq 1 -o "$2" == "status" ]; then
        current_mode=$(cat /sys/devices/system/cpu/intel_pstate/no_turbo)
        if [ $current_mode -eq 0 ]; then
            echo 'turbo boost is enabled'
        else
            echo 'turbo boost is disabled'
        fi
    elif ! [ "$2" == "0" -o "$2" == "1" ]; then
        echo "error: unknown parameter: $2" >&2
        exit 1
    else
        if [ $2 -eq 1 ]; then
            if [ $(cat /sys/devices/system/cpu/intel_pstate/no_turbo) -eq 0 ]; then
                echo 'turbo boost is already enabled.' >&2
                logger --tag mbpfan --priority user.warn "unable to change intel_turbo_boost value. requirements already satisfied."
                exit 1
            else
                check-permission
                echo 0 > /sys/devices/system/cpu/intel_pstate/no_turbo
                echo 'turbo boost is enabled'
                logger --tag mbpfan --priority user.info "successfully enabled intel_turbo_boost."
            fi
        else
            if [ $(cat /sys/devices/system/cpu/intel_pstate/no_turbo) -eq 1 ]; then
                echo 'turbo boost is already disabled.' >&2
                logger --tag mbpfan --priority user.warn "unable to change intel_turbo_boost value. requirements already satisfied."
                exit 1
            else
                check-permission
                echo 1 > /sys/devices/system/cpu/intel_pstate/no_turbo
                logger --tag mbpfan --priority user.info "successfully disabled intel_turbo_boost."
                echo 'turbo boost is disabled'
            fi
        fi
    fi
elif [ "$1" == "help" ]; then
    echo 'usage: mbpfan [option]'
    echo -e '\nOPTIONS'
    echo -e " status\t\t\t\tshow detail about current profiles."
    echo -e "   show <profile [...]>\t\tshow detail about specific profiles."
    echo -e "   list\t\t\t\tshow available profiles."
    echo -e "    set [profile]\t\tupdate new profile for mbpfan."
    echo -e "    get <name|speed|temp>\tget current profile infomations."
    echo -e "\t\t\t\t\`name\`\t\t\t\tshow current profile name."
    echo -e "\t\t\t\t\`speed\` [min|max|cnt]\t\tshow preset for fan speed."
    echo -e "\t\t\t\t\`temp\` [low|high|max|cnt]\tshow preset for temp."
    echo -e "    new [source] <name>\t\tcreate new profile."
    echo -e "   link [source] <name>\t\tlinking exist profile."
    echo -e "   edit [name ...]\t\tedit specific or current profile."
    echo -e "  turbo [1|0]\t\t\tenable(1) or disable(0) Intel turbo boost."
    echo -e " remove <name ...>\t\tdelete specific profile."
    echo -e " rename [old] <new>\t\trename specific or current profile."
    echo -e "   help\t\t\t\tshow this help."
    echo -e "\n※ Some options will request super-user permission."
    echo -e '\nAVAILABLE PROFILES'
    ls /etc/mbpfan.d | grep -v $(basename `readlink /etc/mbpfan.conf`) | sed 's/^/ /'
else
    echo "unknown options: $@" >&2
    exit 1
fi
