#!/bin/bash

if [ "$(uname)" != "Linux" ]; then
    echo "$(uname -srvmpio) is not supported. This script only works on Linux. " >&2
    exit 1
fi

if [ "$(id -u)" != "0" ]; then
    echo "$USER is not authorized to run this script. Please run this script an authenticated user." >&2
    exit 1
fi

if [ x"$NET_TARGET_INTERFACE_UNIT" == x ]; then
    echo "Network target interface can not be null. Please set 'NET_TARGET_INTERFACE_UNIT' environment variable." >&2
    exit 1
fi

while true; do
    echo "Checking internet connection to www.google.com..."
    ping -c 1 -W 1 -q "www.google.com" &> /dev/null
    if [ $? != 0 ]; then
        echo "No internet connection."
        ifconfig $NET_TARGET_INTERFACE_UNIT down && ifconfig $NET_TARGET_INTERFACE_UNIT up
        if [ $? != 0 ]; then
            echo "fatal: Unable to reload $NET_TARGET_INTERFACE_UNIT network driver." >&2
            echo -e "\tThis system will automatically reboot as soon as possible." >&2
            sleep 2
            reboot
        fi
    else
        echo "You have an internet connection."
    fi

    sleep $(shuf -i 10-20 -n 1)
done
