#!/bin/bash

if [ -x /usr/sbin/poweroff -o ! "$(uname)" != "Linux" ]; then
    exit 1
fi

echo -e "\033[0;1mAre you sure you want to shut down your computer now?\n\t\t\033[m(cancel/poweroff)\n"
echo -e "\033[33;6mWARN\033[0;6m: Running this command will disconnect all remote connections."
echo -e "\tYou can restart the system later by interacting with the device's power button or using the WOL function.\033[m"
echo -n "If you do nothing, the computer will shut down automatically in 00 seconds."

for((i=60; i>=0; i--)); do
    if [ $i -gt 9 ]; then
        echo -en "\b\b\b\b\b\b\b\b\b\b\b$i seconds."
    elif [ $i -eq 9 ]; then
        echo -en "\b\b\b\b\b\b\b\b\b\b\b $i seconds."
    else
        echo -en "\b\b\b\b\b\b\b\b\b\b$i seconds."
    fi
    read -t 1 userAbort
    if [ "$userAbort" == "shut down" -o "$userAbort" == "poweroff" ]; then
        break
    elif [ "$userAbort" == "cancel" -o "$userAbort" == "exit" ]; then
        echo "Abort."
        exit 2
    fi
done

echo ""
if [ "$(id -u)" == "0" ]; then
    /usr/sbin/poweroff
else
    sudo /usr/sbin/poweroff
fi
