#!/bin/bash

target_path=
target_name=
inst_location=
launch_date=$(date '+%Y-%m-%d_%H%M%S')
window_type=

if [ "$1" == "help" -o "$1" == "--help" ]; then
    echo "USAGE: <target> file"
    echo "SUPPORTED TARGET"
    echo "- service"
    echo "- target"
    exit 0
elif [ $# -lt 2 -o $# -gt 3 ]; then
    echo "USAGE: <target> file"
    exit 1
elif [ "$1" != "target" -a "$1" != "service" ]; then
    echo "error: unable to convert $(basename "$2").$1 to systemd type. please see \`help\`" >&2
    exit 1
fi

if ! [ -r "$2" ]; then
    echo "systemd-inst: cannot access '$2': no such file or directory." >&2
    exit 1
fi

target_path=$(realpath "$2")
target_name=$(basename "$2")

if [ $# -eq 2 ]; then
    echo "This script will install $target_name.$1 to /etc/systemd/system"
elif [ $# -eq 3 ]; then
    if ! [ -r "$3" ]; then
        echo "systemd-inst: cannot access '$3': no such file or directory." >&2
        exit 1
    fi

    inst_location=$(realpath "$3")
    echo "This script will install $target_name.$1 to $inst_location"
fi

echo -n "Are you wish continue to install $1? (y/N) > "
read n
if ! [ "$n" == "Y" -o "$n" == "y" ]; then
    echo "Abort."
    exit 1
fi

echo -n "Please type description: "
read desc

echo -n "This $target_name.$1 requires GUI (y/N) > "
read n
if [ "$n" == "y" -o "$n" == "Y" ]; then
    window_type="graphical.target"
else
    window_type="multi-user.target"
fi

echo "# Generated systemd-inst by., Copyright (c) 2024 Hyeongmin Kim." > /tmp/systemd-inst-$launch_date
echo "# For more infomation $1 syntax, follow this url: https://www.freedesktop.org/software/systemd/man/devel/systemd.service.html" >> /tmp/systemd-inst-$launch_date
echo "" >> /tmp/systemd-inst-$launch_date
echo "[Unit]" >> /tmp/systemd-inst-$launch_date
echo "Description=$desc" >> /tmp/systemd-inst-$launch_date
echo "# Uncomment lines below if your program should access internet" >> /tmp/systemd-inst-$launch_date
echo "# Requires=network-online.target" >> /tmp/systemd-inst-$launch_date
echo "# After=network.target" >> /tmp/systemd-inst-$launch_date
echo "" >> /tmp/systemd-inst-$launch_date
echo "[Service]" >> /tmp/systemd-inst-$launch_date
echo "Type=simple" >> /tmp/systemd-inst-$launch_date
echo "ExecStart=$target_path" >> /tmp/systemd-inst-$launch_date
echo "# ExecReload=$target_path --reload" >> /tmp/systemd-inst-$launch_date
echo "# ExecStop=$target_path --stop" >> /tmp/systemd-inst-$launch_date
echo "" >> /tmp/systemd-inst-$launch_date
echo "[Install]" >> /tmp/systemd-inst-$launch_date
echo "WantedBy=$window_type" >> /tmp/systemd-inst-$launch_date
echo "# Uncomment lines below if your program should access third-party daemons" >> /tmp/systemd-inst-$launch_date
echo "# RequiredBy=" >> /tmp/systemd-inst-$launch_date

echo -n "Would you like edit your $target_name.$1 config file? (y/N) > "
read n
if [ "$n" == "y" -o "$n" == "Y" ]; then
    vi /tmp/systemd-inst-$launch_date
fi

if [ $# -eq 2 ]; then
    echo "Installing /etc/systemd/system/$target_name.$1..."
    sudo mv /tmp/systemd-inst-$launch_date "/etc/systemd/system/$target_name.$1"
elif [ $# -eq 3 ]; then
    echo "Installing $inst_location/$target_name.$1..."
    sudo mv /tmp/systemd-inst-$launch_date "$inst_location/$target_name.$1"
fi

if [ -r /tmp/systemd-inst-$launch_date ]; then
    echo "The $target_name.$1 installation process might failed or corrupted." >&2
    rm /tmp/systemd-inst-$launch_date
    exit 1
fi

systemctl status $target_name
echo -n "Would you like enable your $target_name.$1? (Y/n) > "
read n
if ! [ "$n" == "N" -o "$n" == "n" ]; then
    sudo systemctl enable $target_name.$1
fi

echo -n "Would you like start your $target_name.$1? (Y/n) > "
read n
if ! [ "$n" == "N" -o "$n" == "n" ]; then
    sudo systemctl start $target_name.$1
fi

